
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F,fig.width = 10)
```

```{r eval=FALSE, include=FALSE}
rm(list = ls())
library(readxl)
med <- read_excel(path = "input/DTP_NCI60_ZSCORE.xlsx",skip = 7)
colnames(med) <- med[1,]
med <- med[-1,-c(67,68)]
table(med$`FDA status`)

med <- med[med$`FDA status` %in% c("FDA approved","Clinical trial"),]
med <- med[,-c(1,3:6)]
write.csv(med,file = "input/drug.csv")
```

```{r eval=FALSE, include=FALSE}
rna <- read_excel(path = "input/RNA__RNA_seq_composite_expression.xls", skip = 9)
colnames(rna) <- rna[1,]
rna <- rna[-1,-c(2:6)]
write.csv(rna,file = "input/rna_exp.csv")
```

```{r}
rm(list = ls())
library(impute)
library(limma)

drug <- read.csv(file = "input/drug.csv",row.names = 1)
drug <- as.matrix(drug)
rownames(drug) <- drug[,1]
drug <- drug[,2:ncol(drug)]
dimnames <- list(rownames(drug),colnames(drug))
data <- matrix(as.numeric(as.matrix(drug)),nrow=nrow(drug),dimnames=dimnames)

mat <- impute.knn(data,colmax=0.9)
drug <- mat$data
drug <- avereps(drug)

rna_exp <- read.csv(file = "input/rna_exp.csv",row.names = 2)
rna_exp <- rna_exp[,-1]

marker <- c("RGS2")
exp <- rna_exp[marker,]

```

```{r}
outTab <- data.frame()

for(Gene in row.names(exp)){
  x <- as.numeric(exp[Gene,])
  for(Drug in row.names(drug)){
     y <- as.numeric(drug[Drug,])
     corT <- cor.test(x,y,method="pearson")
     cor <- corT$estimate
     pvalue <- corT$p.value
      if(pvalue < 0.05){
        outVector <- cbind(Gene,Drug,cor,pvalue)
        outTab <- rbind(outTab,outVector)
      }}}

outTab <- outTab[order(as.numeric(as.vector(outTab$pvalue))),]
```


```{r}

library(ggplot2)
library(ggpubr)

Pca_drug <- c("Vincristine", "Estramustine", "Colchicine", "Cediranib", "(+)-JQ1", "I-BET-151")
outTab <- outTab[outTab$Drug %in% Pca_drug,]

plotList_1 <- list()
corPlotNum <- 5
if(nrow(outTab)<corPlotNum){
 corPlotNum=nrow(outTab)
}

for(i in 1:corPlotNum){
 Gene <- outTab[i,1]
 Drug <- outTab[i,2]
 x <- as.numeric(exp[Gene,])
 y <- as.numeric(drug[Drug,])
 cor <- sprintf("%.03f",as.numeric(outTab[i,3]))
 pvalue=0
 if(as.numeric(outTab[i,4])<0.001){
   pvalue="p<0.001"
 }else{
   pvalue=paste0("p=",sprintf("%.03f",as.numeric(outTab[i,4])))
 }
 df1 <- as.data.frame(cbind(x,y))
 p1=ggplot(data = df1, aes(x = x, y = y))+
   geom_point(size=1)+
   stat_smooth(method="lm",se=FALSE, formula=y~x)+
   labs(x="Expression",y="IC50",title = paste0(Gene,", ",Drug),subtitle = paste0("Cor=",cor,", ",pvalue))+
   theme(axis.ticks = element_blank(), axis.text.y = element_blank(),axis.text.x = element_blank())+
   theme_bw()
 plotList_1[[i]]=p1
}
```


```{r}

plotList_2 <- list()
corPlotNum <- 5
if(nrow(outTab)<corPlotNum){
 corPlotNum=nrow(outTab)
}

for(i in 1:corPlotNum){
 Gene <- outTab[i,1]
 Drug <- outTab[i,2]
 x <- as.numeric(exp[Gene,])
 y <- as.numeric(drug[Drug,])
 df1 <- as.data.frame(cbind(x,y))
 colnames(df1)[2] <- "IC50"
 df1$group <- ifelse(df1$x > median(df1$x), "high", "low")
 compaired <- list(c("low", "high"))
 p1 <- ggboxplot(df1,
                 x = "group", y = "IC50",
                 fill = "group", palette = c("#00AFBB", "#E7B800"),
                 add = "jitter", size = 0.5,
                 xlab = paste0("The_expression_of_", Gene),
                 ylab = paste0("IC50_of_", Drug)) +
   stat_compare_means(comparisons = compaired,
                      method = "wilcox.test",
                      symnum.args=list(cutpoints = c(0, 0.001, 0.01, 0.05, 1),
                                       symbols = c("***", "**", "*", "ns")))
 plotList_2[[i]]=p1
}
```

```{r}
nrow <- ceiling(sqrt(corPlotNum))
ncol <- ceiling(corPlotNum/nrow)
p <- ggarrange(plotlist=plotList_1,nrow=2,ncol=3)
ggarrange(plotlist=plotList_2,nrow=2,ncol=3)

ggsave(plot = p,filename = "S4.pdf",path="stepout/",width = 30,height = 22.5, units = "cm")
```
