
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F,fig.width = 10)
options(stringsAsFactors = F)
```

```{r}
rm(list = ls())
library(survminer)
library(survival)
library(timeROC)
library(ggplot2)
library(rms)
library(stringr)
library(tidyverse)
library(tableone)
library(forestplot)
```

```{r}
load('stepout/Risk_Score.Rdata')

dt <- train

dt$age<- dt$age/365
dt$age<- abs(dt$age)
dt$age <- as.numeric(dt$age)

dt$stage_T[str_detect(dt$stage_T,"T1")] <- "1"
dt$stage_T[str_detect(dt$stage_T,"T2")] <- "2"
dt$stage_T[str_detect(dt$stage_T,"T3")] <- "3"
dt$stage_T[str_detect(dt$stage_T,"T4")] <- "4"
dt$stage_T<- as.numeric(dt$stage_T)

dt$stage_N[str_detect(dt$stage_N,"N0")] <- "0"
dt$stage_N[str_detect(dt$stage_N,"N1")] <- "1"
dt$stage_N<- as.numeric(dt$stage_N)

dt$stage_M[str_detect(dt$stage_M,"M0")] <- "0"
dt$stage_M[str_detect(dt$stage_M,"M1")] <- "1"
dt$stage_M<- as.numeric(dt$stage_M)

table(dt$stage_T)
table(dt$stage_N)
table(dt$stage_M)

table(dt$race)
dt$race <- ifelse(dt$race == 'WHITE',1,
           ifelse(dt$race == 'BLACK OR AFRICAN AMERICAN',2,
           ifelse(dt$race == 'ASIAN',3,
           ifelse(dt$race == 'AMERICAN INDIAN OR ALASKA NATIVE',4,NA))))

dt$G_grade<- as.numeric(dt$G_grade)

save(dt,file = c('stepout/TCGA_cox_clean.Rdata'))
```

```{r}

dt <- dt[,c("BCR_times","BCR_event","score")]
head(dt)

timeROC <- with(dt,
timeROC(T = BCR_times,
delta = BCR_event,
marker = score, 
cause = 1, 
times = c(1,3,5), 
ROC = TRUE, 
iid = TRUE, 
weighting = "marginal")) 
print(timeROC)

timeROC$AUC

confint(timeROC, level = 0.95)$CI_AUC

df <- data.frame(FPR = as.numeric(timeROC$FP),
TPR = as.numeric(timeROC$TP),
time = rep(as.factor(c(1,3,5)), each = nrow(timeROC$TP)))
head(df)

mytheme <- theme(axis.title = element_text(size = 13),
axis.text = element_text(size = 11),
plot.title = element_text(size = 14,
hjust = 0.5,
face = "bold"),
legend.title = element_text(size = 13),
legend.text = element_text(size = 11),
legend.background = element_rect(linetype = 1, size = 0.25, colour = "black"),
legend.position = c(1, 0),
legend.justification = c(1, 0))

p <- ggplot() +
geom_line(data = df,aes(x = FPR, y = TPR, color = time), size = 1) +
geom_line(aes(x = c(0,1),y = c(0,1)),color = "grey") +
scale_color_manual(name = NULL, values = c("#e76254","#376795","#f8ac8c"),
labels = c("1 Years(AUC = 0.632)" ,"3 Years(AUC = 0.635)", "5 Years(AUC = 0.538)"))+
theme_bw() +
mytheme +
labs(x = "1 - Specificity (FPR)",
y = "Sensitivity (TPR)")
p

ggsave(plot = p,filename = "roc tcga.pdf",path="stepout/",width = 10.4,height = 10, units = "cm")
```


```{r}
rm(list = ls())
load('stepout/TCGA_cox_clean.Rdata')

Ucox1 <- coxph(Surv(BCR_times, BCR_event) ~ G_grade, data = dt)
Ucox2 <- coxph(Surv(BCR_times, BCR_event) ~ stage_T, data = dt)
Ucox3 <- coxph(Surv(BCR_times, BCR_event) ~ stage_N, data = dt)
Ucox4 <- coxph(Surv(BCR_times, BCR_event) ~ score, data = dt)
Ucox5 <- coxph(Surv(BCR_times, BCR_event) ~ age, data = dt)
Ulist <- list(Ucox1,Ucox2,Ucox3,Ucox4,Ucox5)

Ulist <- lapply(X = Ulist,function(x){
  U2 <- summary(x)
  U3 <- as.data.frame(t(round(U2$conf.int[, c(1, 3, 4)], 2)))
  U4 <- ShowRegTable(
  x,                   
  exp = TRUE,            
  digits = 2,            
  pDigits = 3,           
  printToggle = TRUE,     
  quote = FALSE,         
  ciFun = confint        
)
result <- cbind(U3, U4)
result <- rownames_to_column(result, var = "Variable")

})

Ucox <- data.table::rbindlist(Ulist)
Ucox$Variable <- c("GLEASON Score","Path T Stage","Path N Stage","Risk Score","Age")
colnames(Ucox)[5] <- "HR(95%CI)"
names1 <- as.data.frame(t(colnames(Ucox)))
colnames(names1) <- colnames(Ucox)
Ucox <- rbind(names1,Ucox)

fig <- forestplot(
  Ucox[, c(1, 5, 6)],   
  mean = Ucox[, 2],    
  lower = Ucox[, 3],  
  upper = Ucox[, 4],   
  zero = 1,              
  boxsize = 0.1,         
  graph.pos = "right",            
  hrzl_lines = list(              
    "1" = gpar(lty = 1, lwd = 2), 
    "2" = gpar(lty = 2),          
    "7" = gpar(lwd = 2, lty = 1, columns = c(1:4)) 
    ),
  graphwidth = unit(.25, "npc"),   
  xlab = "",
  xticks = c(-0.5, 1, 3, 5, 7),
  is.summary = c(T, F, F, F, F, F, F),  
  txt_gp = fpTxtGp(                
    label = gpar(cex = 1),      
    ticks = gpar(cex = 0.8),      
    xlab = gpar(cex = 1),       
    title = gpar(cex = 1)       
  ),
  lwd.zero = 1,                   
  lwd.ci = 1.5,                    
  lwd.xaxis = 2,                   
  lty.ci = 1.5,                   
  ci.vertices = T,                
  ci.vertices.height = 0.2,       
  clip = c(0.1, 8),              
  ineheight = unit(8, 'mm'),       
  line.margin = unit(8, 'mm'),     
  colgap = unit(6, 'mm'),          
  fn.ci_norm = "fpDrawDiamondCI",  
  col = fpColors(                 
    box = "#e76254",               
    lines = "#376795",              
    zero = "black"                 
      )          
)

pdf(file = "stepout/S2A.pdf",width=6, height=4)
fig
dev.off()
```

```{r}

Mcox <- coxph(Surv(BCR_times, BCR_event) ~G_grade + score + age   , data = dt)

summary(Mcox)
x <- summary(Mcox)
colnames(x$conf.int)

multi1 <- as.data.frame(round(x$conf.int[, c(1, 3, 4)], 2))

multi2 <- ShowRegTable(
  Mcox,                
  exp = TRUE,             
  digits = 2,               
  pDigits = 3,              
  printToggle = TRUE,       
  quote = FALSE,           
  ciFun = confint          
)

result <- cbind(multi1, multi2)

result <- rownames_to_column(result, var = "Variable")

result$Variable <- c("GLEASON Score","Risk Score","Age")
colnames(result)[5] <- "HR(95%CI)"
names2 <- as.data.frame(t(colnames(result)))
colnames(names2) <- colnames(result)
result <- rbind(names2,result )


fig <- forestplot(
  result[, c(1, 5, 6)],  
  mean = result[, 2],   
  lower = result[, 3],    
  upper = result[, 4],  
  zero = 1,              
  boxsize = 0.1,         
  graph.pos = "right",            
  hrzl_lines = list(             
    "1" = gpar(lty = 1, lwd = 2), 
    "2" = gpar(lty = 2),         
    "5" = gpar(lwd = 2, lty = 1, columns = c(1:4)) 
    ),
  graphwidth = unit(.25, "npc"),   
  xlab = "",
  xticks = c(-0.5, 1, 3, 5, 7), 
  is.summary = c(T, F, F, F),  
  txt_gp = fpTxtGp(                
    label = gpar(cex = 1),      
    ticks = gpar(cex = 0.8),       
    xlab = gpar(cex = 1),      
    title = gpar(cex = 1)        
  ),
  lwd.zero = 1,                   
  lwd.ci = 1.5,                    
  lwd.xaxis = 2,                  
  lty.ci = 1.5,                    
  ci.vertices = T,               
  ci.vertices.height = 0.2,      
  clip = c(0.1, 8),               
  ineheight = unit(8, 'mm'),     
  line.margin = unit(8, 'mm'),     
  colgap = unit(6, 'mm'),         
  fn.ci_norm = "fpDrawDiamondCI",  
  col = fpColors(                 
    box = "#e76254",               
    lines = "#376795",             
    zero = "black"               
      )          
)

pdf(file = "stepout/S2B.pdf",width=6, height=2.6)
fig
dev.off()
```

```{r}
rm(list = ls())
load('stepout/TCGA_cox_clean.Rdata')
head(dt)

dd <- datadist(dt)
options(datadist = "dd")

f <- cph(Surv(BCR_times, BCR_event) ~ G_grade + score + age , data = dt,
x = T,y = T,surv = T,time.inc=1)
f

surv <- Survival(f)
surv1 <- function(x) surv(1,x) 
surv3 <- function(x) surv(3,x) 
surv5 <- function(x) surv(5,x)

nom <- nomogram(f,
fun = list(surv1,surv3,surv5),
lp = F,
funlabel = c("1-year survival","3-year survival","5-year survival"),
fun.at = c(0.1,seq(0.05,1,by = 0.1),1))

pdf(file = "stepout/S2C.pdf",width=8, height=6)
plot(nom)
dev.off()

```

```{r}

p <- calibrate(f, 
                  cmethod='KM', 
                  method="boot", 
                  u=1, 
                  m=100,
                  B=1000) 
plot(p,
     add=F,
     conf.int=T,
     subtitles = F,
     cex.subtitles=0.8, 
     lwd=2,
     lty=1,
     errbar.col="#e76254",
     xlim=c(0.0,1),
     ylim=c(0.0,1),
     xlab="Nomogram-prediced DFS",
     ylab="Observed DFS" ,
     col="#e76254")

p <- calibrate(f, 
                  cmethod='KM', 
                  method="boot", 
                  u=3, 
                  m=100, 
                  B=1000) 
plot(p,
     add=T,
     conf.int=T,
     subtitles = F,
     cex.subtitles=0.8, 
     lwd=2,
     lty=1,
     errbar.col="#376795",
     xlim=c(0.0,1),
     ylim=c(0.0,1),
     xlab="",
     ylab="",
     col="#376795")

p <- calibrate(f, 
                  cmethod='KM', 
                  method="boot", 
                  u=5, 
                  m=100, 
                  B=1000) 
plot(p,
     add=T,
     conf.int=T,
     subtitles = F,
     cex.subtitles=0.8, 
     lwd=2,
     lty=1,
     errbar.col="#f8ac8c",
     xlim=c(0.0,1),
     ylim=c(0.0,1),
     xlab="",
     ylab="",
     col="#f8ac8c")

```

