
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F,fig.width = 10)
options(stringsAsFactors = F)
```

```{r}
rm(list = ls())
library(limma)
library(clusterProfiler)
library(gggsea)
library(GSVA)
library(enrichplot)
library(stringr)
library(ggthemes)
library(ggplot2)
library(FactoMineR)
library(factoextra) 
library(ggpubr)
library(GSEABase)
library(fgsea)
library(org.Hs.eg.db)
library(tidyverse)
library(dplyr)
library(survival)
library(survminer)
```

```{r}
load(file = "stepout/TCGA_data.rdata")
group<- read.csv(file = "stepout/Group.csv")

Group = ifelse(str_detect(group$risk,"High"),"High","Low")
Group = factor(Group,levels = c("High","Low"))
```

```{r}

marker <- c("RGS2","RNF39")

tumor <- as.data.frame(t(exp_tumor[rownames(exp_tumor) %in% marker,]),optional = T)
normal<- as.data.frame(t(exp_normal[rownames(exp_normal) %in% marker,]),optional = T)

tumor$group <- "Tumor"
normal$group <- "Normal"
tdata <- rbind.data.frame(tumor,normal)
tdata$group <- as.factor(tdata$group)

p1 = ggplot(tdata,aes(x = group, y = tdata[,"RGS2"],color= group))+
  geom_boxplot(size=1,width=0.5) + 
  xlab("Group") +
  ylab("RGS2_Expression") +
  scale_color_manual(values=c('Normal'='#376795','Tumor'='#e76254'))+
  theme_classic()+
  stat_compare_means(comparisons = list( c("Normal", "Tumor")))+
  theme(legend.position = 'none')
p1

p2 = ggplot(tdata,aes(x = group, y = tdata[,"RNF39"],color= group))+
  geom_boxplot(size=1,width=0.5) + 
  xlab("Group") +
  ylab("RNF39_Expression") +
  scale_color_manual(values=c('Normal'='#376795','Tumor'='#e76254'))+
  theme_classic()+
  stat_compare_means(comparisons = list( c("Normal", "Tumor")))
p2

library(patchwork)

p3 <- p1+p2

ggsave(plot = p3,filename = "dif_exp.pdf",path="stepout/",width = 12.6,height = 10, units = "cm")
```

```{r}
design=model.matrix(~Group)
fit=lmFit(exp_tumor,design)
fit=eBayes(fit)
deg=topTable(fit,coef=2,number = Inf)

logFC_t= 0.5 
P.Value_t = 0.05
k1 = (deg$P.Value < P.Value_t)&(deg$logFC < -logFC_t)
k2 = (deg$P.Value < P.Value_t)&(deg$logFC > logFC_t)
deg <- mutate(deg,change = ifelse(k1,"down",ifelse(k2,"up","stable")))
table(deg$change)

write.csv(deg,file ="stepout/deg_tcga.csv")
```

```{r}
library(ggrepel)
deg2 <- deg
deg2$symbol<-  rownames(deg2)

p <- ggplot(data = deg2, 
            aes(x = logFC, 
                y = -log10(P.Value))) +
  geom_point(alpha=0.4, size=3.5, 
             aes(color=change)) +
  ylab("-log10(Pvalue)")+
  scale_color_manual(values=c("#376795", "#eeeeee","#e76254"))+
  geom_vline(xintercept=c(-logFC_t,logFC_t),lty=4,col="black",lwd=0.8) +
  geom_hline(yintercept = -log10(P.Value_t),lty=4,col="black",lwd=0.8) +
  theme_bw();p

ggsave(plot = p ,filename = "F3A.pdf",path="stepout/",width = 12.5,height = 10, units = "cm")

colnames(deg2)[4] <- "v"
deg2$v <- -log10(deg2$v)

p <- ggscatter(deg2, 
          x = "logFC", 
          y ="v",
          ylab="-log10(P.value)",
          size=2.0,
          label = "symbol",
          color = "change",
          palette = c('#376795',"#eeeeee", '#e76254'),
          label.select = c("RGS2", "RNF39")
          )

```

```{r}
ids <- bitr(row.names(deg),fromType="SYMBOL",toType="ENTREZID", OrgDb="org.Hs.eg.db",drop = TRUE)
deg$symbol <- row.names(deg)
deg <- merge(deg,ids,by.x = "symbol",by.y="SYMBOL")
deg2 <- deg[!deg$change=="stable",]
write.csv(deg2,file = "stepout/deg2.csv")

kk <- enrichKEGG(gene=deg2$ENTREZID,
                    organism='hsa',
                    pvalueCutoff=0.05,
                    pAdjustMethod="BH",
                    qvalueCutoff=0.05)

dat <- kk@result %>% filter(pvalue<0.05) 
```

```{r}

enrichment_fold = apply(dat,1,function(x){
  GeneRatio=eval(parse(text=x["GeneRatio"]))
  BgRatio=eval(parse(text=x["BgRatio"]))
  enrichment_fold=round(GeneRatio/BgRatio,2)
  enrichment_fold
})
identical(rownames(dat),names(enrichment_fold))
dat$enfold <- enrichment_fold 

dat=dat[order(dat$Count,decreasing = F),]
dat <- dat[dat$Count>=15,]

dat2 <- dat[c(1,3,5,7,9,13,17,19,20,21,23,28,29,31:34,36:38),]

gk_plot <- ggplot(dat2,aes( x=reorder(Description, Count), y = Count,fill = pvalue)) +
    geom_bar(stat = "identity",width=0.8) +
    coord_flip() +
    scale_fill_gradient(low = "#e76254",high ="#376795" )+
    labs(x="", y="Count") +
    theme_pander()  +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line.x = element_line(size = 0.3, colour = "black"),
          axis.ticks.length.x = unit(-0.20, "cm"),
          axis.text.x = element_text(margin = margin(t = 0.3, unit = "cm")),
          axis.ticks.x = element_line(colour = "black",size = 0.3) ,  
          axis.ticks.y = element_blank(),
          axis.text.y  = element_text(hjust=0),
          panel.background = element_rect(fill=NULL, colour = 'white')
          )
gk_plot

ggsave(plot = gk_plot ,filename = "F3B.pdf",path="stepout/",width = 12.5,height = 10, units = "cm")

```

```{r}

bulk_all <-enrichGO(deg2$ENTREZID,
              OrgDb = 'org.Hs.eg.db',
              keyType = "ENTREZID",
              ont = "ALL",
              pvalueCutoff = 0.05,
              qvalueCutoff = 0.05,
              readable = T)

go <- as.data.frame(bulk_all)
go <- go[go$Count>25,]
go_MF<-go [go $ONTOLOGY=="MF",][1:7,]
go_CC<-go [go $ONTOLOGY=="CC",][1:7,]
go_BP<-go [go $ONTOLOGY=="BP",][1:7,]

go_enrich_df <- data.frame(ID=c(go_BP$ID, go_CC$ID, go_MF$ID),
                         Description=c(go_BP$Description, go_CC$Description, go_MF$Description),
                         GeneNumber=c(go_BP$Count, go_CC$Count, go_MF$Count),
                         type=factor(c(rep("biological process", 7), rep("cellular component", 7),rep("molecular function",7)),levels=c("molecular function", "cellular component", "biological process")))

go_enrich_df$number <- factor(rev(1:nrow(go_enrich_df)))


labels = go_enrich_df$Description
names(labels) = rev(1:nrow(go_enrich_df))

CPCOLS <- c("#376795", "#f8ac8c", '#e76254')

p <- ggplot(data=go_enrich_df, aes(x=number, y=GeneNumber, fill=type)) +
  geom_bar(stat="identity", width=0.8) + coord_flip() + 
  scale_fill_manual(values = CPCOLS) + theme_test() + 
  scale_x_discrete(labels=labels) +
  xlab("") + 
  theme(axis.text=element_text(face = "bold", color="black")) +
  labs(title = "");p

ggsave(plot = p ,filename = "F3C.pdf",path="stepout/",width = 16,height = 10, units = "cm")
```

